/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mauro' at '08/10/16 12.16' with Gradle 2.9
 *
 * @author mauro, @date 08/10/16 12.16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
